// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPyZdWwl2i17i3f861XXc1njl9ym2lIgc',
    appId: '1:92999931839:web:700f24d4723a6db3ac330a',
    messagingSenderId: '92999931839',
    projectId: 'khelo-dev-8040e',
    authDomain: 'khelo-dev-8040e.firebaseapp.com',
    storageBucket: 'khelo-dev-8040e.appspot.com',
    measurementId: 'G-W9Y0Z1TN2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8mdOgjpM9J6tI-4D195GThJV26lGm-w',
    appId: '1:92999931839:android:6bb53b7449b2b928ac330a',
    messagingSenderId: '92999931839',
    projectId: 'khelo-dev-8040e',
    storageBucket: 'khelo-dev-8040e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdjFi8wkE4vf69Wqa45juwLxPEREIOD0',
    appId: '1:92999931839:ios:06a5606f88805af9ac330a',
    messagingSenderId: '92999931839',
    projectId: 'khelo-dev-8040e',
    storageBucket: 'khelo-dev-8040e.appspot.com',
    iosBundleId: 'com.example.khelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdjFi8wkE4vf69Wqa45juwLxPEREIOD0',
    appId: '1:92999931839:ios:984233dbd06405beac330a',
    messagingSenderId: '92999931839',
    projectId: 'khelo-dev-8040e',
    storageBucket: 'khelo-dev-8040e.appspot.com',
    iosBundleId: 'com.example.khelo.RunnerTests',
  );
}
