name: Dart Format & Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: subosito/flutter-action@v2.12.0
        name: Set up Flutter SDK
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd data && flutter clean && flutter pub get
          cd ../style && flutter clean && flutter pub get
          cd ../khelo && flutter clean && flutter pub get
          cd ..

      - name: Lint test
        run: |
          cd data && flutter analyze --fatal-infos
          cd ../style && flutter analyze --fatal-infos
          cd ../khelo && flutter analyze --fatal-infos
          cd ..