name: Dart Format & Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: subosito/flutter-action@v2.12.0
        name: Set up Flutter SDK
        with:
          channel: 'stable'
          cache: true

      - name: Retrieve the secret and decode it to file
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
          GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
          FIREBASE_JSON_BASE64: ${{ secrets.FIREBASE_JSON_BASE64 }}
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          CONFIG_BASE64: ${{ secrets.CONFIG_BASE64 }}
          API_KEYS_BASE64: ${{ secrets.API_KEYS_BASE64 }}
        run: |
          cd khelo
          echo $FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options.dart  
          echo $GOOGLE_SERVICE_INFO_PLIST_BASE64 | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo $FIREBASE_JSON_BASE64 | base64 --decode > firebase.json
          echo $GOOGLE_SERVICES_JSON_BASE64 | base64 --decode > android/app/google-services.json
          echo $CONFIG_BASE64 | base64 --decode > ios/Config.xcconfig
          echo $API_KEYS_BASE64 | base64 --decode > ../data/lib/utils/api_keys.dart

      - name: Install dependencies
        run: |
          cd data && flutter clean && flutter pub get
          cd ../style && flutter clean && flutter pub get
          cd ../khelo && flutter clean && flutter pub get
          cd ..

      - name: Lint test
        run: |
          cd khelo
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos

          cd ../data
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos

          cd ../style
          dart format . --set-exit-if-changed
          dart analyze --fatal-infos

          cd ..