name: Analyze

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: subosito/flutter-action@v2.12.0
        name: Set up Flutter SDK
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd app
          flutter clean
          flutter pub get

          cd ../data
          flutter clean
          flutter pub get

          cd ../style
          flutter clean
          flutter pub get

          cd ..

      - name: Lint test
        run: |
          cd app
          dart analyze --fatal-infos

          cd ../data
          dart analyze --fatal-infos

          cd ../style
          dart analyze --fatal-infos

          cd ..