name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: subosito/flutter-action@v2.12.0
        name: Set up Flutter SDK
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          cd khelo
          flutter clean
          flutter pub get

          cd ../data
          flutter clean
          flutter pub get

          cd ../style
          flutter clean
          flutter pub get

          cd ..


      - name: Build android APK
        run: |
          cd khelo
          file='VERSION'
          fileData=$(cat $file)
          IFS='.'
          read -a versionValue <<< "$fileData"
          buildNumber=$(( ${versionValue[0]} * 1000000 + ${versionValue[1]} * 10000 + CI_PIPELINE_IID ))
          IFS=''
          buildName="${versionValue[0]}.${versionValue[1]}.$CI_PIPELINE_IID"

          echo "Generating android build $buildName $buildNumber"
          flutter build apk --release --build-number=$buildNumber --build-name=$buildName
          mv build/app/outputs/apk/release/*.apk .
          cd ..

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: khelo.apk
          path: khelo/*.apk
          if-no-files-found: error