name: Deploy Firebase Function

on: push
#  push:
#    branches:
#      - main
#  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: subosito/flutter-action@v2.12.0
        name: Set up Flutter SDK
        with:
          channel: 'stable'
          cache: true

      - uses: actions/setup-node@v2
        name: Setup Node.js
        with:
          node-version: 18

      - uses: actions/cache@v3
        name: Cache Dependencies
        id: cache-dependencies
        with:
          path: |
            ~/.npm
            ~/.cache/firebase
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        working-directory: khelo/functions
        run: |
          npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Prepare Google Application Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          FIREBASE_JSON_BASE64: ${{ secrets.FIREBASE_JSON_BASE64 }}
        run: |
          cd khelo
          echo $GOOGLE_APPLICATION_CREDENTIALS | base64 --decode > functions/google-application-credentials.json
          echo $FIREBASE_JSON_BASE64 | base64 --decode > firebase.json

      - name: Verify Credentials Path
        run: echo $GOOGLE_APPLICATION_CREDENTIALS

      - name: Deploy Firebase functions
        run: |
          cd khelo
          firebase deploy --only functions --non-interactive --debug

      - name: Remove credentials file
        if: success() || failure()
        run: |
          cd khelo
          rm functions/google-application-credentials.json